# ?maven profile ? Spring Profile ????
spring:
  profiles:
    active: @env@

# mapper.xml?????
mybatis:
  mapper-locations: classpath*:mapper/*.xml

#????
pagehelper:
  helper-dialect: mysql #??sql???
  reasonable: true #???????,??false,????????pageNum<1??????,??pageNum>pages???????
  support-methods-arguments: true #??????mapper??????????? ,???false
  params: count=countSql
